### PR TITLE
Prevent piston/door bug

### PR DESCRIPTION
**Pull request by Maxopoly**

### CODE REVIEW

**Comment by Maxopoly** [comment]
@ProgrammerDan So apparently poortea found out that pistons can pop reinforced doors if they push against their upper half. This fixes that.

**Comment by ProgrammerDan** [comment]
Very clever, thanks

**Comment by poortea** [comment]
do i get a reward if i tell you other bugs of equal importance:/

https://www.youtube.com/watch?v=Wmq9JP7FwEU pls sub

**Comment by ProgrammerDan** [comment]
I won't preban you from any of my future servers, that's one potential
reward :)

**Comment by poortea** [comment]
oh boy future servers

have you fixed the /logout dupe with chests

**Comment by Maxopoly** [comment]
Probably not

**Comment by vtesterlwg** [comment]
@Maxopoly its already fixed from when u updated spigot

**Pull request merged**
