### PR TITLE
Added support for exclusive reinforcement types

### PR DESCRIPTION
**Pull request by soerxpso**
To make a reinforcement type an exclusive reinforcement type, add a stringlist called reinforceables to that reinforcement type in the config.yml and list the blocks that the reinforcement type should be able to reinforce. For example

 emerald:
  material: EMERALD
  requirements: 1
  return: 1
  percent_chance: 100
  hit_points: 1000
  mature_time: 500
  scale_amount: 0
  reinforceables:
   \- CHEST
   \- COBBLESTONE
  lore:

would make it so emerald can only reinforce chests and cobblestone. Reinforcement types that do not contain a reinforceables stringlist will act normally.

### CODE REVIEW

**Comment by soerxpso** [comment]
It's definitely covering ctf and ctr, but I did miss ctar. I'll add that now real quick.

**Comment by soerxpso** [comment]
Everything should be good now. I'm fairly certain that this covers every case where a reinforcement can be created (/ctr, /ctf and /ctar). Let me know if you think of another case that I should add a check to.

**Comment by ShadedJon** [comment]
This looks fantastic.

I'm going to make so many evil things with this :+1: 

Great job!

**Comment by ProgrammerDan** [comment]
Replaced with #9 , merged, thank you again!

**Pull request closed without merging**
